var sgdata=new function(){this.sg_loggedInElements = [];this.sg_clickIdList=[];this.sg_customizedElementList=[];this.sg_loginformList =[];this.sg_signupformList =[];this.sg_urlList=[];
this.gaPropertyId="";this.sgAccountType=88;this.userIdSlot=5;
this.sg_signupformList.push(["login.aspx?ReturnUrl=/shop/shippingaddress.aspx","login.aspx?ReturnUrl=%2fshop%2fshippingaddress.aspx","txtName"]);
this.sg_signupConfirmationPage="shop/shippingaddress.aspx";
this.sg_loginformList.push(["login.aspx?ReturnUrl=/shop/shippingaddress.aspx","login.aspx?ReturnUrl=%2fshop%2fshippingaddress.aspx","txtName"]);
this.sg_loggedInElements.push(["shop/shippingaddress.aspx","form","",""]);
this.sg_urlList.push(["",""]);
this.sg_clickIdList.push(["*","mainCategory","Global DD::See All Stores"]);
this.sg_clickIdList.push(["*","Books & Stationery","Global DD::Books & Stationery"]);
this.sg_clickIdList.push(["*","Baby Products & Toys","Global DD::Baby Products & Toys"]);
this.sg_clickIdList.push(["*","A/LI[4]/UL/LI/UL/DIV#seeAllStores/DIV#mainCategory/DIV#columnSideHead/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Global DD::Cameras"]);
this.sg_clickIdList.push(["*","Cakes & Cookies, Chocolates, Sweets & Flowers","Global DD::Cakes & Cookies, Chocolates, Sweets & Flowers"]);
this.sg_clickIdList.push(["*","Electronics & Computers","Global DD::Electronics & Computers"]);
this.sg_clickIdList.push(["*","Food & Health","Global DD::Food & Health"]);
this.sg_clickIdList.push(["*","Gift Articles & Personalised Gifts","Global DD::Gift Articles & Personalised Gifts"]);
this.sg_clickIdList.push(["*","Handicrafts, Arts & Spirituality","Global DD::Handicrafts, Arts & Spirituality"]);
this.sg_clickIdList.push(["*","Home Appliances, Televisions & Music System","Global DD::Home Appliances, Televisions & Music System"]);
this.sg_clickIdList.push(["*","Jewellery & Watches","Global DD::Jewellery & Watches"]);
this.sg_clickIdList.push(["*","A/LI[12]/UL/LI/UL/DIV#seeAllStores/DIV#mainCategory/DIV#columnSideHead/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Global DD::Mobiles"]);
this.sg_clickIdList.push(["*","Perfumes & Cosmetics","Global DD::Perfumes & Cosmetics"]);
this.sg_clickIdList.push(["*","Sports & Footwear","Global DD::Sports & Footwear"]);
this.sg_clickIdList.push(["*","A/DIV[5]/DIV[3]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::20 Percent Off Apparel"]);
this.sg_clickIdList.push(["*","A/DIV[8]/DIV/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::99 to 999 Monsoon Appliances"]);
this.sg_clickIdList.push(["*","ahrefshopcart","Header::Cart Icon"]);
this.sg_clickIdList.push(["*","A/LI/UL/DIV#menu/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Tab - Rakhi Gifts"]);
this.sg_clickIdList.push(["*","A/LI[2]/UL/DIV#menu/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Tab - Apparel"]);
this.sg_clickIdList.push(["*","A/LI[4]/UL/DIV#menu/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Tab - Books"]);
this.sg_clickIdList.push(["*","A/LI[5]/UL/DIV#menu/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Tab - Flowers"]);
this.sg_clickIdList.push(["*","Pick & Drop Service","Home Page::Spotlight Tab - Pick & Drop"]);
this.sg_clickIdList.push(["*","A/DIV/DIV#slides/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Link - Rakhi Gifts"]);
this.sg_clickIdList.push(["*","A/DIV[2]/DIV#slides/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Link - Apparel"]);
this.sg_clickIdList.push(["*","A/DIV[4]/DIV#slides/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Link - Books"]);
this.sg_clickIdList.push(["*","A/DIV[5]/DIV#slides/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Link - Flowers"]);
this.sg_clickIdList.push(["*","A/DIV[6]/DIV#slides/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Link - Pick & Drop"]);
this.sg_clickIdList.push(["*","Logout","Header::Logout"]);
this.sg_clickIdList.push(["*","Login","Header::Login"]);
this.sg_clickIdList.push(["*","A/DIV#fbloginliMaster/DIV#fbloginbtn/LI/UL/DIV#socialMediaLinks/DIV#header/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Header::Facebook Login"]);
this.sg_clickIdList.push(["*","A/DIV#fbloginli/TD/TR[2]/TBODY/TABLE/TD[3]/TR/TBODY/TABLE/DIV#sublogintable/DIV/TD/TR[2]/TBODY/TABLE/TD/TR/TBODY/TABLE/DIV[4]/FORM#form1/BODY/HTML","Login Page::Facebook Login"]);
this.sg_clickIdList.push(["*","INPUT#butlogin/SPAN/P/TD[2]/TR[5]/TBODY/TABLE/DIV#sublogintable/DIV/TD/TR[2]/TBODY/TABLE/TD/TR/TBODY/TABLE/DIV[4]/FORM#form1/BODY/HTML","Login Page::Login"]);
this.sg_clickIdList.push(["*","INPUT#butlogin/DIV#divcontinue/DIV/DIV#login_container/DIV#signin1/DIV#leftorder/DIV#holderstore/DIV#containerstore1/FORM#form1/BODY/HTML","Cart Login Page::Login Cart"]);
this.sg_clickIdList.push(["*","A/DIV#fbloginli/TD/TR/TBODY/TABLE/DIV#FBbtnDiv/DIV#login_container/DIV#signin1/DIV#leftorder/DIV#holderstore/DIV#containerstore1/FORM#form1/BODY/HTML","Cart Login Page::Facebook Login Cart"]);
this.sg_clickIdList.push(["*","topFestivalImage-link3","Header::Rakhi"]);
this.sg_clickIdList.push(["*","A[2]/DIV[5]/DIV#navCrossStores/DIV#header/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Header::Rakhi - Free Gifts"]);
this.sg_clickIdList.push(["*","A/LI[3]/UL/DIV#slider/DIV#content/DIV#container/TD/TR/TBODY/TABLE/DIV/DIV#containerPage_rakhi/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Rakhi Home Page::Spotlight1 - Pooja Thali"]);
this.sg_clickIdList.push(["*","A/LI[2]/UL/DIV#slider/DIV#content/DIV#container/TD/TR/TBODY/TABLE/DIV/DIV#containerPage_rakhi/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Rakhi Home Page::Spotlight2 - Loving Brother"]);
this.sg_clickIdList.push(["*","A/TD/TR/TBODY/TABLE#table_01/TD[2]/TR/TBODY/TABLE/DIV/DIV#containerPage_rakhi/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Rakhi Home Page::Feature Banner - Most Popular Gift"]);
this.sg_clickIdList.push(["*","A/LI[3]/UL/DIV#menu/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Tab - Appliances"]);
this.sg_clickIdList.push(["*","A/DIV[3]/DIV#slides/DIV#galleryFoot/DIV#gallery/DIV/DIV[2]/DIV[3]/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","Home Page::Spotlight Link - Appliances"]);
this.sg_clickIdList.push(["*","A#Signup/DIV#newSec/DIV/DIV#login_container/DIV#signin1/DIV#leftorder/DIV#holderstore/DIV#containerstore1/FORM#form1/BODY/HTML","Cart Login Page::Sign up"]);
this.sg_clickIdList.push(["*","A/SPAN/TD[2]/TR[3]/TBODY/TABLE#ext_User/DIV#login_section/DIV/DIV#login_container/DIV#signin1/DIV#leftorder/DIV#holderstore/DIV#containerstore1/FORM#form1/BODY/HTML","Cart Login Page::Forgot Password"]);
this.sg_customizedElementList.push(["*","SPAN","RootPath","SPAN/SPAN#lblDescription7/SPAN#__tab_Tab7/SPAN/SPAN/SPAN#Tab7_tab/DIV#TabContain_header/DIV#TabContain/DIV/DIV#tabpanelcontain/DIV#fdpBelowSpot/DIV#mainContainer/DIV#containerPageFoot/DIV#containerPage/FORM#form1/BODY/HTML","May We Recommend"]);
this.sg_customizedElementList.push(["*","SPAN","RootPath","SPAN#ContentPlaceHolder1_SpecificValuesHolder_ctl00_DivCompareBut/DIV[2]/DIV[2]/DIV#ContentPlaceHolder1_SpecificValuesHolder_ctl00_CompareDiv/DIV[2]/DIV#ContentPlaceHolder1_SpecificValuesHolder_ctl00_divIsHTML/DIV#skuAreaSm/DIV#browseRtArea/DIV#belowSpot/DIV#ContentPlaceHolder1_upPnl1/DIV#mainContainer/DIV#containerPage/FORM#form1/BODY/HTML","Compare Button"]);
this.sg_customizedElementList.push(["*","A","RootPath","A/DIV#ContentPlaceHolder1_ordStatusDetdiv/TD/TR[7]/TBODY/TABLE/TD/TR/TBODY/TABLE/DIV/DIV/DIV/DIV#ContentPlaceHolder1_maindiv/DIV#mainContainer/DIV#containerPage/FORM#form1/BODY/HTML","Failure Response Page"]);
}
